language: generic

sudo: required
services: docker

before_install:
  - docker build -t baileys20055/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baileys20055/docker-react npm run test